### ISSUE TITLE
ImportError: No module named OpenGL

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/deepin-screenshot#16]
Latest updated **deepin-screenshot 3.1.8** on Manjaro/Archlinux fails with
```
[bernhard@manjaro-deepin ~]$ deepin-screenshot
Traceback (most recent call last):
  File "/usr/bin/deepin-screenshot", line 15, in <module>
    from OpenGL import GL
ImportError: No module named OpenGL
```

**Comment by oberon2007** [comment]
Looks like we miss the dependency **python-opengl**! @felixonmars

**Comment by oberon2007** [comment]
Also some more of the listed dependencies are not installed.
Do we need **python-pyqt5**, too? **python-wnck**?? **deepin-gettext-tools**?

**Comment by felixonmars** [comment]
Well, we are on python2, and `python2-pyqt5`/`python2-wnck` are already in the dependencies. I'm checking others.

**Comment by felixonmars** [comment]
No other problem spot, I am pushing 3.1.8-2 to Arch with `python2-opengl` added as a dependency.

**Comment by oberon2007** [comment]
Thank you! Works fine with **python2-opengl** installed :)
