### ISSUE TITLE
not run

### ISSUE THREAD

**Issue by 93Alliance** [linuxdeepin/deepin-screenshot#77]
deepin-screenshot: relocation error: /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2: symbol _ZN14QWidgetPrivate15setStyle_helperEP6QStylebb version Qt_5_PRIVATE_API not defined in file libQt5Widgets.so.5 with link time reference

**Comment by 93Alliance** [comment]
Ubuntu 18.04

**Comment by BLumia** [comment]
If you are building the most recent source code (master), you may need to build its newer depts at the same time. If you just would like to build the source code, try fetch the same version as the one provided by your distro, or checkout the source code to the same tag :)
