### ISSUE TITLE
ctrl + alt + a causes horrible screen flickering / tearing (Nvidia)

### ISSUE THREAD

**Issue by mitchellkrogza** [linuxdeepin/deepin-screenshot#84]
Hi there

I have latest version of screenshot. After using Ctrl+alt+a there is terrible screen flickering and tearing all over the place that is only resolved with a reboot. I have an Nvidia card. It also a big black border around the program window that was screenshotted. 
![2020-03-03_11-22](https://user-images.githubusercontent.com/9961541/75761263-737c3a00-5d41-11ea-90cc-11749d980ab2.png)
 

kwin-5.18.2-1-x86_64
deepin-screenshot-5.0.0-2-x86_64

**Comment by mitchellkrogza** [comment]
Here's a screen capture

![output2](https://user-images.githubusercontent.com/9961541/75763925-bc35f200-5d45-11ea-8cc7-517993233419.gif)

**Comment by BLumia** [comment]
The screenshot tool do nothing with this issue. I guess there are something wrong with the wm backend or your graphics card driver installation.

Try install `systemsettings5` and goto "Compositor > Rendering backend" and switch between different backends and see if it helps. If it still happens, maybe you should try check your graphics card driver then.

**Comment by mitchellkrogza** [comment]
Thank you so much @BLumia I installed SystemSettings5 switched to XRender as the rendering backend and now it is perfect :tada: thanks so much
