### ISSUE TITLE
请增加等比例截图功能

### ISSUE THREAD

**Issue by acgtyrant** [linuxdeepin/deepin-screenshot#9]
我记得 QQ 内置截图工具，在截图的时候按 Alt, 截图大小会自动变成正方形，即等比例。

**Comment by pangpangpang3** [comment]
这是个好的建议，下个版本会考虑添加此功能，感谢对深度截图的关注！

**Comment by acgtyrant** [comment]
我靠，长达一年的反射神经！

**Comment by acgtyrant** [comment]
@farseerfc 曰：你需要 reminder.

**Comment by pangpangpang3** [comment]
抱歉，我是才看到你的建议，你可以去深度的论坛反馈一些需求，那里的回复比较及时．http://bbs.deepin.org/

**Comment by acgtyrant** [comment]
发现已经支持了，不错。
